# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StatusTrend < Formula
  desc "Terminal dashboard for monitoring vendor status pages"
  homepage "https://github.com/aflansburg/status-trend"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aflansburg/status-trend/releases/download/v0.1.0/status-trend_0.1.0_darwin_amd64.tar.gz"
      sha256 "6ff9297182cef1d82214642593eef1e5e755d69dece709cab9166fe21ebe6fff"

      define_method(:install) do
        bin.install "status-trend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aflansburg/status-trend/releases/download/v0.1.0/status-trend_0.1.0_darwin_arm64.tar.gz"
      sha256 "8c76f551c7840b8058015395406a2aeaa8454463d163164171d00522f9d51355"

      define_method(:install) do
        bin.install "status-trend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aflansburg/status-trend/releases/download/v0.1.0/status-trend_0.1.0_linux_amd64.tar.gz"
      sha256 "b2ed1ffcdfabe1486d850c63c035757ce0d042238df2ec4c2b6601309888b792"
      define_method(:install) do
        bin.install "status-trend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aflansburg/status-trend/releases/download/v0.1.0/status-trend_0.1.0_linux_arm64.tar.gz"
      sha256 "c5005998a79465015a6272c1ba13de91d8358f192287b53e516617d5a6c832fb"
      define_method(:install) do
        bin.install "status-trend"
      end
    end
  end
end
