# This file was generated by GoReleaser. DO NOT EDIT.
cask "status-trend" do
  name "status-trend"
  desc "Terminal dashboard for monitoring vendor status pages"
  homepage "https://github.com/aflansburg/status-trend"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "status-trend"

  on_macos do
    on_intel do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_darwin_amd64.tar.gz"
      sha256 "899afce406bbd9f04fdba8002238d170c45d0a067986e1a6c39634023139f86d"
    end
    on_arm do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_darwin_arm64.tar.gz"
      sha256 "67826b01faa0b040b4723382698e0dedab7e7981603b4f6fa2eee0a0675ea7b1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_linux_amd64.tar.gz"
      sha256 "d7e660ba5d9ddf93b2372be122454d0e415ca9ac7d968069c4e99d0116f0d3cf"
    end
    on_arm do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_linux_arm64.tar.gz"
      sha256 "5d47ab8d500353f1cab7fa375908eddd07402813aae8918a2537f42da79770d6"
    end
  end

  # No zap stanza required
end
