# This file was generated by GoReleaser. DO NOT EDIT.
cask "status-trend" do
  name "status-trend"
  desc "Terminal dashboard for monitoring vendor status pages"
  homepage "https://github.com/aflansburg/status-trend"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "status-trend"

  on_macos do
    on_intel do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_darwin_amd64.tar.gz"
      sha256 "5df56e6cc863a71fd9cb888264324ea745972c467c5306b6acdfa4047b265721"
    end
    on_arm do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_darwin_arm64.tar.gz"
      sha256 "2d1a7dfac2b3912d4fe300143f3b5a6e943cf4728886542ad97f9ca7eda056e3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_linux_amd64.tar.gz"
      sha256 "0f083d3a208ecbc3bdf46bdbe6f7279cc44fc11c0cc36091a0375949a523ed1e"
    end
    on_arm do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_linux_arm64.tar.gz"
      sha256 "9cf2234f427d21f47aa8d178cc8f10625fc101123c32b10bd205b82396ee9d51"
    end
  end

  # No zap stanza required
end
