# This file was generated by GoReleaser. DO NOT EDIT.
cask "status-trend" do
  name "status-trend"
  desc "Terminal dashboard for monitoring vendor status pages"
  homepage "https://github.com/aflansburg/status-trend"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "status-trend"

  on_macos do
    on_intel do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_darwin_amd64.tar.gz"
      sha256 "68d91af0dd10f8912116849adcbbf38585c741464fb73814a1a870dc78e9007d"
    end
    on_arm do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_darwin_arm64.tar.gz"
      sha256 "56e7561d7ad33ab88ce7fc33ae6cec2c2ac6af95ecd79f34c22acc1a2898049f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_linux_amd64.tar.gz"
      sha256 "0c246026958dd5770bf36bdeb4513acb67a1e74a951f1e0b4058536260608bc5"
    end
    on_arm do
      url "https://github.com/aflansburg/status-trend/releases/download/v#{version}/status-trend_#{version}_linux_arm64.tar.gz"
      sha256 "8d3f9c27a152101ebb31f9b87eaad757dcc811ad55c650c99f3183615b232076"
    end
  end

  # No zap stanza required
end
